services:
  - type: web
    name: hhanalyst
    runtime: docker
    dockerfilePath: ./python_analyzer/Dockerfile
    dockerContext: ./python_analyzer
    plan: free
    region: frankfurt
    envVars:
      - key: PORT
        value: "8090"
